# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_o6dEDmhSgnFB5xeocQ6M6pN5fNCPE8
"""

from bs4 import BeautifulSoup

ITEM_HTML = '''<html><head></head><body>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
    <article class="product_pod">
            <div class="image_container">
                    <a href="catalogue/a-light-in-the-attic_1000/index.html"><img src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg" alt="A Light in the Attic" class="thumbnail"></a>
            </div>
                <p class="star-rating Three">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>
            <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
            <div class="product_price">
        <p class="price_color">£51.77</p>
<p class="instock availability">
    <i class="icon-ok"></i>
        In stock
</p>
    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>
            </div>
    </article>
</li>
</body></html>
'''

SIMPLE_HTML = '''<html>
<head></head>
<body>
<h1>This is a title</h1>
<p class="subtitle">Lorem ipsum dolor sit amet. Consectetur edipiscim elit.</p>
<p>Here's another p without a class</p>
<ul>
    <li>Rolf</li>
    <li>Charlie</li>
    <li>Jen</li>
    <li>Jose</li>
</ul>
</body>
</html>'''

soup = BeautifulSoup(SIMPLE_HTML, 'html.parser')

print(soup.prettify())

h1 = soup.find_all('h1')
print(h1)

h1_one = soup.find('h1')
h1_one.string

def getlist():
  li_list = soup.find_all('li')
  li_string = [string.string for string in li_list]
  print(li_string)

getlist()

def subtitle():
  para = soup.find('p',{'class':'subtitle'})
  print(para.string)
subtitle()

def get_paras():
  para = soup.find('p')
  print(para.string)

get_paras()

def get_all_para():
  para = soup.findAll('p')
  para = [p.string for p in para]
  print(para)
get_other_para()

def get_specific():
  para = soup.findAll('p',{'class':''})
  para = [i.string for i in para]
  return para
get_specific()

def get_specific_class():
  para = soup.find_all('p')
  para = [i.string for i in para if 'subtitle' not in i.attrs.get('class',[])]
  print(para)

get_specific_class()

